### ISSUE TITLE
database root in sample SimpleSchema

### ISSUE THREAD

**Issue by ahoy-jon** [divarvel/jDbT#1]
Is the database node necessary for the input definition ?

```
user:
  firstname: String(50)
  lastname: String(50)
  nickname: String(20)
#... 
```

Could be enough.
